[package]
name = "ic-stable-structures"
version.workspace = true
edition.workspace = true

[dependencies]
ic-exports = { path = "../ic-exports"}
thiserror = { workspace = true }

[dev-dependencies]
anyhow = "1"
candid = { workspace = true }
did = { path = "./tests/did" }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-exports = { path = "../ic-exports", features = ["ic-test-state-machine"]}
once_cell = { workspace = true }
serde = { workspace = true }

[features]
# When this features is enabled, the default structures exported at root level
# use the heap. Otherwise the stable storage is used
default-heap-structures = []
# Enables the integration tests based on ic-test-state-machine
state-machine = []