[package]
name = "ic-stable-structures"
version.workspace = true
edition.workspace = true

[dependencies]
ic-exports = { path = "../ic-exports" }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = "1"
candid = { workspace = true }
did = { path = "./tests/did" }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
once_cell = "1.18"
serde = { workspace = true }


[features]
state-machine = ["ic-exports/state-machine"]
