[package]
name = "ic-payments"
version = "0.1.0"
edition = "2021"

[features]
state-machine = ["ic-exports/state-machine"]

[dependencies]
ic-exports = { path = "../ic-exports" }
ic-canister = { path = "../ic-canister/ic-canister" }
ic-storage = { path = "../ic-storage" }
ic-stable-structures = { path = "../ic-stable-structures/" }
serde = "1.0"
candid = "0.8"
thiserror = "1.0"
async-recursion = "1.0.2"

[dev-dependencies]
tokio = { version = "1.0", features = ["rt", "macros"] }
