[workspace]
members = [
    "ic-exports",
    "ic-factory",
    "ic-auction",
    "ic-metrics",
    "ic-helpers",
    "ic-payments",
    "ic-payments/test-payment-canister",
    "ic-stable-structures",
    "ic-storage",
    "ic-storage/ic-storage-derive",
    "ic-canister/ic-canister",
    "ic-canister/ic-canister-macros",
    "ic-canister/tests/canister-a",
    "ic-canister/tests/canister-b",
    "ic-canister/tests/canister-c",
    "ic-canister/tests/canister-d",
    "ic-canister/tests/canister-e",
    "cmc-mock",
]

[package]
name = "canister-sdk"
version.workspace = true
edition.workspace = true

[workspace.package]
version = "0.3.53"
edition = "2021"

[features]
default = []
factory-api = ["ic-factory?/export-api"]
auction-api = ["ic-auction?/export-api"]
metrics-api = ["ic-metrics/export-api"]
auction = ["dep:ic-auction"]
factory = ["dep:ic-factory"]


[dependencies]
ic-exports = { path = "./ic-exports" }
ic-auction = { path = "./ic-auction", optional = true }
ic-factory = { path = "./ic-factory", optional = true }
ic-canister = { path = "./ic-canister/ic-canister" }
ic-storage = { path = "./ic-storage" }
ic-helpers = { path = "./ic-helpers" }
ic-metrics = { path = "./ic-metrics" }

[workspace.dependencies]
async-recursion = "1.0.2"
async-trait = "0.1"
auto_ops = "0.3"
binread = "2.2"
crypto-bigint = { version = "0.4", features = ["serde"] }
cycles-minting-canister = { git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712" }
getrandom = { version = "0.2", features = ["custom"] }
hex = "0.4"
k256 = "0.11"
lazy_static = "1"
libsecp256k1 = "0.7"
num-bigint = "0.4"
num-traits = "0.2"
proc-macro2 = "1.0"
quote = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.2"
serde_cbor = "0.11.2"
serde_json = "1.0"
serde_tokenstream = "0.1"
sha2 = "0.9"
syn = "1.0"
thiserror = "1.0"
tokio = "1.0"
tokio-test = "0.4"

# IC dependencies
candid = "0.8"
ic-agent = { version = "0.24" }
ic-base-types = { git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712" }
ic-cdk = "0.8"
ic-cdk-macros = "0.6"
ic-cdk-timers = "0.1"
ic-crypto-sha = { git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712" }
ic-ic00-types = { git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712" }
ic-icrc1 = { git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712" }
ic-icrc1-index = { git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712" }
ic-ledger-core = { git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712" }
ic-nns-common = { git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712" }
ic-stable-structures = "0.5"
ic-state-machine-tests = { git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712" }
ic-types = { git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712" }
icp-ledger = { git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712" }
ic-kit = { git = "https://github.com/infinity-swap/ic-kit", tag = "v0.4.9" }
ledger-canister = { git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712" }
