[workspace]
members = [
  "ic-exports",
  "ic-factory",
  "ic-auction",
  "ic-metrics",
  "ic-helpers",
  "ic-stable-storage",
  "ic-storage",
  "ic-storage/ic-storage-derive",
  "ic-canister/ic-canister",
  "ic-canister/ic-canister-macros",
  "ic-canister/tests/canister_a",
  "ic-canister/tests/canister_b",
  "ic-canister/tests/canister_c",
]

[package]
edition = "2021"
name = "canister-sdk"
version = "0.3.12"

[features]
default = []
factory_api = ["ic-factory?/export_api", "factory"]
auction_api = ["ic-auction?/export_api", "auction"]
auction = ["dep:ic-auction"]
factory = ["dep:ic-factory"]

[dependencies]
ic-exports = { path = "./ic-exports" }
ic-auction = { path = "./ic-auction", optional = true }
ic-factory = { path = "./ic-factory", optional = true }
ic-canister = { path = "./ic-canister/ic-canister" }
ic-storage = { path = "./ic-storage" }
ic-helpers = { path = "./ic-helpers" }
ic-metrics = { path = "./ic-metrics" }
