[workspace]
members = [
    "ic-exports",
    "ic-factory",
    "ic-auction",
    "ic-metrics",
    "ic-helpers",
    "ic-stable-structures",
    "ic-storage",
    "ic-storage/ic-storage-derive",
    "ic-canister/ic-canister",
    "ic-canister/ic-canister-macros",
    "ic-canister/tests/canister-a",
    "ic-canister/tests/canister-b",
    "ic-canister/tests/canister-c",
    "ic-canister/tests/canister-d",
    "ic-canister/tests/canister-e",
]

[package]
edition = "2021"
name = "canister-sdk"
version = "0.3.12"

[features]
default = []
factory-api = ["ic-factory?/export-api"]
auction-api = ["ic-auction?/export-api"]
metrics-api = ["ic-metrics/export-api"]
auction = ["dep:ic-auction"]
factory = ["dep:ic-factory"]


[dependencies]
ic-exports = { path = "./ic-exports" }
ic-auction = { path = "./ic-auction", optional = true }
ic-factory = { path = "./ic-factory", optional = true }
ic-canister = { path = "./ic-canister/ic-canister" }
ic-storage = { path = "./ic-storage" }
ic-helpers = { path = "./ic-helpers" }
ic-metrics = { path = "./ic-metrics" }