[package]
name = "ic-auction"
version = "0.1.0"
edition = "2021"

[features]
default = []
no_api = []

[dependencies]
ic-cdk = "0.5"
candid = "=0.7.14" # Because there is a build issue with ic_types::principal::PrincipalError 
ic-kit = { git = "https://github.com/infinity-swap/ic-kit", tag = "v0.4.6" }
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
ic-canister = { path = "../ic-canister/ic-canister", package = "ic-canister" }
ic-canister-macros = { path = "../ic-canister/ic-canister-macros", package = "ic-canister-macros" }
ic-storage = { path = "../ic-storage", package = "ic-storage" }
ic-helpers = { path = "../ic-helpers", package = "ic-helpers" }