[package]
name = "icrc-ledger-types"
version.workspace = true
edition.workspace = true

[dependencies]
candid = { workspace = true }
hex = { workspace = true }
serde_bytes = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
num-traits = { workspace = true }
