[package]
name = "ic-storage"
version.workspace = true
edition.workspace = true

[dependencies]
candid = { workspace = true }
ic-exports = { path = "../ic-exports" }
ic-storage-derive = {path = "ic-storage-derive"}
serde = { workspace = true }
thiserror = { workspace = true }
