# A crate with all of the ic exports that is used in other dependencies 
# needed to simplify the process of upgrading ic deps in other projects

[package]
name = "ic-exports"
version.workspace = true
edition.workspace = true

[features]
default = []
ic-test-state-machine = ["flate2", "ic-test-state-machine-client", "log", "once_cell", "reqwest"]
ledger = ["ic-ledger-types"]

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-cdk-timers = { workspace = true }

ic-stable-structures = { workspace = true }

ic-kit = { path = "../ic-kit" }

# Do not remove: This fixes the getrandom deployment in wasm canisters
ic-crypto-getrandom-for-wasm = { path = "../ic-crypto-getrandom-for-wasm" }

# dependencies for `ledger` feature
ic-ledger-types = { workspace = true, optional = true }

# dependencies for `state-machine-test` feature
flate2 = { workspace = true, optional = true }
ic-test-state-machine-client = { workspace = true, optional = true }
log = { workspace = true, optional = true }
once_cell = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true, features = [
  "blocking",
  "gzip",
  "json",
  "rustls-tls",
  "trust-dns",
] }
