# A crate with all of the ic exports that is used in other dependencies 
# needed to simplify the process of upgrading ic deps in other projects

[package]
name = "ic-exports"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.5"
ic-cdk-macros = "0.5"

ic-agent = { version = "0.20", optional = true }

stable-structures = { git = "https://github.com/dfinity/ic", branch = "rc--2022-09-11_18-31" }
ledger-canister = {git = "https://github.com/dfinity/ic", branch = "rc--2022-09-11_18-31"}
ic-ledger-core = {git = "https://github.com/dfinity/ic", branch = "rc--2022-09-11_18-31"}
ic-base-types = {git = "https://github.com/dfinity/ic", branch = "rc--2022-09-11_18-31"}
ic-ic00-types = {git = "https://github.com/dfinity/ic", branch = "rc--2022-09-11_18-31"}
cycles-minting-canister = { git="https://github.com/dfinity/ic",branch="rc--2022-09-11_18-31"}

ic-icrc1-index = { git="https://github.com/dfinity/ic",branch="rc--2022-10-03_18-33"}

ic-kit = { git = "https://github.com/infinity-swap/ic-kit", tag = "v0.4.6" }
