# A crate with all of the ic exports that is used in other dependencies 
# needed to simplify the process of upgrading ic deps in other projects

[package]
name = "ic-exports"
version = "0.2.0"
edition = "2021"

[dependencies]
ic-cdk = { version = "0.6", features = ["timers"]}
ic-cdk-macros = "0.6"

ic-agent = { version = "0.21", optional = true }


ic-stable-structures = {git = "https://github.com/dfinity/stable-structures", commit = "99f50a5b9b7eee48787ff40e16315b7e4287b08d"}
ledger-canister = {git = "https://github.com/dfinity/ic", branch = "rc--2022-10-06_18-31"}
ic-ledger-core = {git = "https://github.com/dfinity/ic", branch = "rc--2022-10-06_18-31"}
ic-base-types = {git = "https://github.com/dfinity/ic", branch = "rc--2022-10-06_18-31"}
ic-ic00-types = {git = "https://github.com/dfinity/ic", branch = "rc--2022-10-06_18-31"}
cycles-minting-canister = { git="https://github.com/dfinity/ic",branch="rc--2022-10-06_18-31"}
ic-icrc1-index = { git="https://github.com/dfinity/ic",branch="rc--2022-10-06_18-31"}
ic-icrc1 = { git="https://github.com/dfinity/ic", branch="rc--2022-10-06_18-31"}

ic-kit = { git = "https://github.com/infinity-swap/ic-kit", tag = "v0.4.7" }

