# A crate with all of the ic exports that is used in other dependencies 
# needed to simplify the process of upgrading ic deps in other projects

[package]
name = "ic-exports"
version = "0.2.0"
edition = "2021"

[features]
default = []
state-machine = ["ic-state-machine-tests"]

[dependencies]
ic-cdk = "0.7"
ic-cdk-macros = "0.6"
ic-cdk-timers =  "0.1"

ic-agent = { version = "0.23", optional = true }


ic-stable-structures = "0.5"
icp-ledger = {git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712"}
ledger-canister = {git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712"}
ic-ledger-core = {git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712"}
ic-base-types = {git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712"}
ic-ic00-types = {git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712"}
cycles-minting-canister = { git="https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712"}
ic-icrc1-index = { git="https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712"}
ic-icrc1 = { git="https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712"}
ic-crypto-sha = { git="https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712"}

ic-kit = { git = "https://github.com/infinity-swap/ic-kit", tag = "v0.4.8-dev" }

ic-state-machine-tests = {git = "https://github.com/dfinity/ic", rev = "36674c853f5515ccad589a042187835219c8b712", optional = true}
