# A crate with all of the ic exports that is used in other dependencies 
# needed to simplify the process of upgrading ic deps in other projects

[package]
name = "ic-exports"
version.workspace = true
edition.workspace = true

[features]
default = []
state-machine = ["ic-state-machine-tests"]
ledger = ["ic-ledger-types"]

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-cdk-timers = { workspace = true }

ic-stable-structures = { workspace = true }

ic-kit = { path = "../ic-kit" }

ic-base-types = { workspace = true }
ic-ic00-types = { workspace = true }

# Do not remove: This fixes the getrandom deployment in wasm canisters
ic-crypto-getrandom-for-wasm = { path = "../ic-crypto-getrandom-for-wasm" }
ic-ledger-types = { workspace = true, optional = true }

ic-state-machine-tests = { workspace = true, optional = true }
