# A crate with all of the ic exports that is used in other dependencies 
# needed to simplify the process of upgrading ic deps in other projects

[package]
name = "ic-exports"
version = "0.2.0"
edition = "2021"

[features]
default = []
state-machine = ["ic-state-machine-tests"]

[dependencies]
ic-cdk = { version = "0.6", features = ["timers"]}
ic-cdk-macros = "0.6"

ic-agent = { version = "0.21", optional = true }


ic-stable-structures = "0.3.0"
icp-ledger = {git = "https://github.com/dfinity/ic", rev = "dcbf401f27d9b48354e68389c6d8293c4233b055"}
ledger-canister = {git = "https://github.com/dfinity/ic", rev = "dcbf401f27d9b48354e68389c6d8293c4233b055"}
ic-ledger-core = {git = "https://github.com/dfinity/ic", rev = "dcbf401f27d9b48354e68389c6d8293c4233b055"}
ic-base-types = {git = "https://github.com/dfinity/ic", rev = "dcbf401f27d9b48354e68389c6d8293c4233b055"}
ic-ic00-types = {git = "https://github.com/dfinity/ic", rev = "dcbf401f27d9b48354e68389c6d8293c4233b055"}
cycles-minting-canister = { git="https://github.com/dfinity/ic", rev = "dcbf401f27d9b48354e68389c6d8293c4233b055"}
ic-icrc1-index = { git="https://github.com/dfinity/ic", rev = "dcbf401f27d9b48354e68389c6d8293c4233b055"}
ic-icrc1 = { git="https://github.com/dfinity/ic", rev = "dcbf401f27d9b48354e68389c6d8293c4233b055"}

ic-kit = { git = "https://github.com/infinity-swap/ic-kit", tag = "v0.4.7" }

ic-state-machine-tests = {git = "https://github.com/dfinity/ic", rev = "dcbf401f27d9b48354e68389c6d8293c4233b055", optional = true}
