# A crate with all of the ic exports that is used in other dependencies 
# needed to simplify the process of upgrading ic deps in other projects

[package]
name = "ic-exports"
version.workspace = true
edition.workspace = true

[features]
default = []
state-machine = ["ic-state-machine-tests"]

[dependencies]
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-cdk-timers =  { workspace = true }

ic-agent = { workspace = true, optional = true }


ic-stable-structures = { workspace = true }
icp-ledger = { workspace = true }
ledger-canister = { workspace = true }
ic-ledger-core = { workspace = true }
ic-base-types = { workspace = true }
ic-ic00-types = { workspace = true }
cycles-minting-canister = { workspace = true }
ic-icrc1-index = { workspace = true }
ic-icrc1 = { workspace = true }
ic-crypto-sha = { workspace = true }
icrc-ledger-types = { workspace = true }

ic-kit = { workspace = true }

ic-state-machine-tests = { workspace = true, optional = true}
