# A crate with all of the ic exports that is used in other dependencies 
# needed to simplify the process of upgrading ic deps in other projects

[package]
name = "ic-exports"
version.workspace = true
edition.workspace = true

[features]
default = []
state-machine = ["ic-state-machine-tests"]
ledger = ["ic-icrc1-ledger", "ic-ledger-canister-core", "ic-ledger-core", "icp-ledger", "icrc-ledger-types"]

[dependencies]
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-kit = { workspace = true }
ic-stable-structures = { workspace = true }

ic-base-types = { workspace = true }
ic-ic00-types = { workspace = true }

ic-icrc1-ledger = { workspace = true, optional = true }
ic-ledger-canister-core = { workspace = true, optional = true }
ic-ledger-core = { workspace = true, optional = true }
icp-ledger = { workspace = true, optional = true }
icrc-ledger-types = { workspace = true, optional = true }

ic-state-machine-tests = { workspace = true, optional = true }
