[package]
name = "ic-canister-macros"
version = "0.2.2"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
lazy_static = "1"
serde = "1.0"
serde_tokenstream = "0.1"

[package.metadata.cargo-udeps.ignore]
ic-exports = { path = "../../ic-exports" }