[package]
name = "ic-canister"
version.workspace = true
edition.workspace = true

[dependencies]
ic-exports = {path = "../../ic-exports" }
ic-canister-macros = { path = "../ic-canister-macros" }

[dev-dependencies]
serde = { workspace = true }
tokio-test = { workspace = true }
