[package]
name = "ic-canister"
version.workspace = true
edition.workspace = true

[dependencies]
ic-canister-macros = { path = "../ic-canister-macros" }
ic-exports = { path = "../../ic-exports" }

[dev-dependencies]
serde = { workspace = true }
