[package]
edition = "2021"
name = "ic-helpers"
version = "0.2.1"

[features]
default = []
agent = ["ic-agent", "garcon"]

[dependencies]
dfn_core = {git = "https://github.com/infinity-swap/ic", branch = "rebased-2022-02-17"}
dfn_protobuf = {git = "https://github.com/infinity-swap/ic", branch = "rebased-2022-02-17"}
ledger-canister = {git = "https://github.com/infinity-swap/ic", branch = "rebased-2022-02-17"}
async-trait = "0.1"
hex = "0.4"
candid = "0.7"
ic-cdk = "0.3"
ic-kit = { git = "https://github.com/infinity-swap/ic-kit" }
num-traits = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_bytes = "0.11.2"
serde_cbor = "0.11.2"
sha2 = "0.10"
ic-types = {git = "https://github.com/infinity-swap/ic", branch = "rebased-2022-02-17"}
ic-ic00-types = {git = "https://github.com/infinity-swap/ic", branch = "rebased-2022-02-17"} 
thiserror = "1.0"
ic-canister = { path = "../ic-canister/ic-canister", package = "ic-canister" }
leb128 = "0.2.5"
ic-agent = { version = "0.16", optional = true }
garcon = { version = "0.2", optional = true}
libsecp256k1 = { version = "0.7", optional = false}
k256 = { version = "0.10" }