[package]
edition = "2021"
name = "ic-helpers"
version = "0.2.1"

[dependencies]
dfn_core = {git = "https://github.com/infinity-swap/ic", branch = "rebased-2022-02-17"}
dfn_protobuf = {git = "https://github.com/infinity-swap/ic", branch = "rebased-2022-02-17"}
ledger-canister = {git = "https://github.com/infinity-swap/ic", branch = "rebased-2022-02-17"}
async-trait = "0.1"
hex = "0.4"
candid = "0.7"
ic-cdk = { git = "https://github.com/aewc/cdk-rs" }
ic-kit = { git = "https://github.com/infinity-swap/ic-kit" }
num-traits = "0.2"
serde = "1.0"
serde_json = "1.0"
sha2 = "0.10"
ic-types = {git = "https://github.com/infinity-swap/ic"}
thiserror = "1.0"
ic-canister = { path = "../ic-canister/ic-canister", package = "ic-canister" }
