[package]
name = "ic-stable-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "=0.7.14"
stable-structures = { git = "https://github.com/dfinity/ic" }
thiserror = "1.0.32"
