on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Clippy, fmt and tests with coverage

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets

  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - name: Machine setup
        run: |
          cargo install ic-wasm
      - name: build
        run: |
          ./scripts/build.sh
      - name: test
        run: |
          ./scripts/test.sh

  integration-test-old:
    name: Integration tests OLD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Machine setup
        run: |
          sudo apt update 
          sudo apt install -y libunwind-dev cmake protobuf-compiler
          sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
          rustup target add wasm32-unknown-unknown
          cargo install ic-wasm

      - name: Run integration tests
        run: |
          ./scripts/build.sh
          ./scripts/test.sh
